{
    "name": "Conciliación cuadrática Guatemala",
    "summary": "Conciliación mensual y XLSX por cuenta contable bancaria",
    "description": "Genera una conciliación cuadrática por compañía y cuenta contable bancaria, reuniendo sus diarios, extractos y partidas pendientes de Odoo. Incluye clasificación, versiones conservadas y exportación XLSX.",
    "version": "19.0.1.1.0",
    "category": "Accounting/Accounting",
    "author": "Silva technologies",
    "license": "LGPL-3",
    "depends": ["account"],
    "external_dependencies": {"python": ["xlsxwriter"]},
    "data": [
        "security/ir.model.access.csv",
        "security/rules.xml",
        "data/concepts.xml",
        "views/configuration_views.xml",
        "views/source_views.xml",
        "views/report_views.xml",
        "wizard/generate_views.xml",
        "views/menus.xml",
    ],
    "installable": True,
    "application": False,
}
